name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake --preset gcc
    - name: build
      run: cmake --build --preset gcc
    - name: test
      run: ctest --preset gcc
